name: Build workflow

on:
  workflow_call:
    inputs:   
      java-version:
        required: false
        type: string
        default: '11'
      app-name:
        required: true
        type: string
jobs:
  build:
    name: Build and Docker Push
    runs-on: ubuntu-latest
    steps:
      - name: Set Image tag
        id: set-image-tag
        run: echo "::set-output name=image_tag::$(echo ${GITHUB_SHA} | cut -c1-7)"
        
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        shell: bash
        run: |
          mvn -B package --file pom.xml
          cp target/${{inputs.app-name}}.jar docker/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      

      - name: Build Docker Image with computed tag
        uses: docker/build-push-action@v3
        with:
          context: docker/
          load: false
          push: true
          tags: chetann/javulna:${{ steps.set-image-tag.outputs.image_tag }}