name: Build workflow

on:
  workflow_call:
    inputs:   
      java-version:
        required: false
        type: string
        default: '11'
    secrets:
        dockerhub-username:
          description: 'Username to login to DockerHub for extended pull rate limits'
          required: false
        dockerhub-token:
          description: 'Personal Access Token to DockerHub for extended pull rate limits'
          required: false
jobs:
  build:
    name: Build and Docker Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        shell: bash
        run: |
          mvn -B package --file pom.xml
          cp target/my-app-1.0-SNAPSHOT.jar docker/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        # if: "${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with latest tag
        uses: docker/build-push-action@v3
        with:
          context: docker/
          load: true
          push: false
          tags: myapp:latest