name: Dependency check usng org.owasp:dependency-check-maven

on:
  workflow_call:
    inputs:   
      java-version:
        required: false
        type: string
        default: '11'
jobs:
  Ivan-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Dependency check with org.owasp:dependency-check-maven
      shell: bash
      run: |
        mvn org.owasp:dependency-check-maven:8.1.0:check

    - name: Archive dependency-check-report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ${{ github.workspace }}/target/dependency-check-report.html