name: Build and Scan Workflow

on:
  workflow_call:
    inputs:   
      java-version:
        required: false
        type: string
        default: '11'
      version:
        type: string
        default: '0.3.0'
    secrets: inherit
jobs:
  build:
    uses: cnighojkar/myworkflows/.github/workflows/build.yml@main
    with:
      java-version: ${{ inputs.java-version }}  
    secrets: inherit
    
  cfn-nag-scan:
    uses: cnighojkar/myworkflows/.github/workflows/cfn-nag-scan.yml@main
    needs: build

  checkov-scan:
    uses: cnighojkar/myworkflows/.github/workflows/checkov-scan.yml@main
    needs: build

  Ivan-scan:
    uses: cnighojkar/myworkflows/.github/workflows/Ivan-scan.yml@main
    needs: build
    with:
      version: ${{ inputs.version }}  
    secrets: inherit