name: Build and Scan Workflow

on:
  workflow_call:
    inputs:   
      java-version:
        required: false
        type: string
        default: '11'
      version:
        type: string
        default: '0.3.0'
    secrets:
        dockerhub-username:
          description: 'Username to login to DockerHub for extended pull rate limits'
          required: false
        dockerhub-token:
          description: 'Personal Access Token to DockerHub for extended pull rate limits'
          required: false
jobs:
  build:
    uses: cnighojkar/myworkflows/.github/workflows/build.yml@main
    with:
      java-version: ${{ inputs.java-version }}  
    secrets:
      dockerhub-username: "${{ secrets.dockerhub-username }}"
      dockerhub-token: "${{ secrets.dockerhub-token }}"


  cfn-nag-scan:
    uses: cnighojkar/myworkflows/.github/workflows/cfn-nag-scan.yml@main
    needs: build

  checkov-scan:
    uses: cnighojkar/myworkflows/.github/workflows/checkov-scan.yml@main
    needs: build

  Ivan-scan:
    uses: cnighojkar/myworkflows/.github/workflows/Ivan-scan.yml@main
    needs: build
    with:
      version: ${{ inputs.version }}  
    secrets: inherit